name: Fetch and update player data
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.12.0]

    steps:
      - name: Check out the repository code on to the machine
      - uses: actions/checkout@v1

      - name: Use Node.js 18.12.0
      - uses: actions/setup-node@v3

      - name: Pull The Player Data
      - run: bash ${GITHUB_WORKSPACE}/cron/run.sh

      - name: Update on Github Pages
      - run: npm run deploy
